### ISSUE TITLE
Test are not passing

### ISSUE THREAD

**Issue by 7--** [vicyyn/tictactoe-anchor#2]
```
$ anchor test
BPF SDK: /home/phil/Desktop/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
warning: unused variable: `x_or_o`
  --> programs/tictactoe/src/structs/game.rs:44:43
   |
44 |         triple.iter().all(|&i| matches!(i,x_or_o))
   |                                           ^^^^^^ help: if this is intentional, prefix it with an underscore: `_x_or_o`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `x_or_o`
  --> programs/tictactoe/src/structs/game.rs:43:17
   |
43 |     pub fn same(x_or_o: BoardItem, triple: &[BoardItem]) -> bool {
   |                 ^^^^^^ help: if this is intentional, prefix it with an underscore: `_x_or_o`

warning: the feature `macro_attributes_in_derive_output` has been stable since 1.57.0 and no longer requires an attribute to enable
 --> programs/tictactoe/src/lib.rs:1:12
  |
1 | #![feature(macro_attributes_in_derive_output)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(stable_features)]` on by default

warning: `tictactoe` (lib) generated 3 warnings
    Finished release [optimized] target(s) in 0.31s
cargo-build-bpf child: /home/phil/Desktop/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/llvm-readelf --dyn-symbols /home/phil/sol-workspace/tictactoe-anchor/target/deploy/tictactoe.so

To deploy this program:
  $ solana program deploy /home/phil/sol-workspace/tictactoe-anchor/target/deploy/tictactoe.so
The program address will default to this keypair (override with --program-id):
  /home/phil/sol-workspace/tictactoe-anchor/target/deploy/tictactoe-keypair.json
Deploying workspace: https://api.devnet.solana.com
Upgrade authority: /home/phil/.config/solana/id.json
Deploying program "tictactoe"...
Program path: /home/phil/sol-workspace/tictactoe-anchor/target/deploy/tictactoe.so...
Program Id: At6uHK3VESCUbFmQJZhaZrwmpL3zaaA5zi55fVhrjx9J

Deploy success

Found a 'test' script in the Anchor.toml. Running it as a test suite!

Running test suite: "/home/phil/sol-workspace/tictactoe-anchor/Anchor.toml"

yarn run v1.22.19
warning package.json: No license field
warning ../../package.json: No license field
$ /home/phil/sol-workspace/tictactoe-anchor/node_modules/.bin/ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'


  tictactoe
    1) Initialize Game
    2) Player o joins
    3) Player x plays


  0 passing (435ms)
  3 failing

  1) tictactoe
       Initialize Game:
     Error: Signature verification failed
      at Transaction.serialize (node_modules/@solana/web3.js/src/transaction.ts:594:13)
      at Provider.send (node_modules/@project-serum/anchor/src/provider.ts:117:22)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Object.rpc [as initializeGame] (node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:24:16)

  2) tictactoe
       Player o joins:
     Error: Signature verification failed
      at Transaction.serialize (node_modules/@solana/web3.js/src/transaction.ts:594:13)
      at Provider.send (node_modules/@project-serum/anchor/src/provider.ts:117:22)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Object.rpc [as playerJoins] (node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:24:16)

  3) tictactoe
       Player x plays:
     TypeError: this._init is not a function
      at Object.BN (node_modules/bn.js/lib/bn.js:39:12)
      at /home/phil/sol-workspace/tictactoe-anchor/tests/tictactoe.ts:41:53
      at Generator.next (<anonymous>)
      at /home/phil/sol-workspace/tictactoe-anchor/tests/tictactoe.ts:31:71
      at new Promise (<anonymous>)
      at __awaiter (tests/tictactoe.ts:27:12)
      at Context.<anonymous> (tests/tictactoe.ts:39:35)
      at processImmediate (node:internal/timers:466:21)



error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by 7--** [comment]
Steps to reproduce (new error):

$git clone git@github.com:vicyyn/tictactoe-anchor.git
$cd tictactoe-anchor
$anchor build
$anchor deploy
anchor deploy
Deploying workspace: https://api.devnet.solana.com
Upgrade authority: /home/phil/.config/solana/id.json
Deploying program "tictactoe"...
Program path: /home/phil/sol-workspace/tictactoe-anchor/target/deploy/tictactoe.so...
=========================================================================
Recover the intermediate account's ephemeral keypair file with
`solana-keygen recover` and the following 12-word seed phrase:
=========================================================================
monitor seven slogan large sense grow fold mechanic apple table fluid eye
=========================================================================
To resume a deploy, pass the recovered keypair as the
[BUFFER_SIGNER] to `solana program deploy` or `solana program write-buffer'.
Or to recover the account's lamports, pass it as the
[BUFFER_ACCOUNT_ADDRESS] argument to `solana program close`.
=========================================================================
Error: Deploying program failed: Error processing Instruction 1: custom program error: 0x1
**There was a problem deploying: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }.**

**Comment by 7--** [comment]
I clones a clean version and I'm trying on localhost network now. I ran `anchor build` which worked but then `anchor deploy` gives this error `Error: Account 2UGHVkEXPHmJidd5GSW7JSRhnaXq3nsoVEhxJDKKDryw has insufficient funds for spend (1.95785496 SOL) + fee (0.00141 SOL)`

I tried `$ solana transfer 2UGHVkEXPHmJidd5GSW7JSRhnaXq3nsoVEhxJDKKDryw 50` but still get the same error. 

I'm able to deploy with solana (not anchor build)
 I ran ```$ solana program deploy /home/phil/sol-workspace/tictactoe-anchor/target/deploy/tictactoe.so
Program Id: 5DzfDQUNYcgXvGH6HMWZPbdt2Z88XHXqTTeyv3NVhwrY```
then put this programId in spots below. 
diffs:
```
Anchor.toml
@@ -1,7 +1,7 @@
 [features]
 seeds = false
 [programs.devnet]
-tictactoe = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
+tictactoe = "5DzfDQUNYcgXvGH6HMWZPbdt2Z88XHXqTTeyv3NVhwrY"
 ```
 ```
 programs/tictactoe/src/lib.rs
@@ -9,7 +9,7 @@ pub use structs::*;
 pub use contexts::*;
 pub use errors::ErrorCode;
 
-declare_id!("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS");
+declare_id!("5DzfDQUNYcgXvGH6HMWZPbdt2Z88XHXqTTeyv3NVhwrY");
 ```
 but then `anchor test` gives the same error as `anchor build`
 ```Error: Account 2UGHVkEXPHmJidd5GSW7JSRhnaXq3nsoVEhxJDKKDryw has insufficient funds for spend (1.95785496 SOL) + fee (0.00141 SOL)```

**Comment by 7--** [comment]
Thank you it's deploying now but I the tests are still failing. 
```
  0 passing (268ms)
  3 failing
  ```
